services:
  diun:
    image: ghcr.io/crazy-max/diun:4
    command: serve
    volumes:
      - data:/data
      - socket-proxy:/socket-proxy:ro
    secrets:
      - discord_webhook_url
    environment:
      TZ: ${TIMEZONE:?error}
      DIUN_WATCH_SCHEDULE: 0 */12 * * * # Every 12 hours
      DIUN_PROVIDERS_DOCKER: true
      DIUN_PROVIDERS_DOCKER_ENDPOINT: unix:///socket-proxy/docker.sock
      DIUN_DEFAULTS_SORTTAGS: semver
      DIUN_DEFAULTS_INCLUDETAGS: ^v?\d+$
      DIUN_NOTIF_DISCORD_WEBHOOKURLFILE: /run/secrets/discord_webhook_url
    labels:
      diun.enable: true
    restart: always

secrets:
  discord_webhook_url:
    environment: DISCORD_WEBHOOK_URL

volumes:
  data:
  socket-proxy:
    external: true
