services:
  diun:
    image: ghcr.io/crazy-max/diun:4
    restart: always
    command: serve
    volumes:
      - data:/data
    secrets:
      - discord_webhook_url
      - gotify_token
    environment:
      TZ: ${TIMEZONE:?error}
      DIUN_WATCH_SCHEDULE: 0 7,17 * * * # 7 AM and 5 PM daily
      DIUN_PROVIDERS_DOCKER: true
      DIUN_PROVIDERS_DOCKER_ENDPOINT: tcp://socket-proxy:2375
      DIUN_DEFAULTS_WATCHREPO: true
      DIUN_DEFAULTS_MAXTAGS: 5
      DIUN_DEFAULTS_SORTTAGS: semver
      DIUN_DEFAULTS_INCLUDETAGS: ^v?\d+$
      DIUN_WATCH_HEALTHCHECKS_BASEURL: https://healthchecks.${INTERNAL_DOMAIN:?error}/ping
      DIUN_WATCH_HEALTHCHECKS_UUID: ${DIUN_HEALTHCHECKS_UUID:?error}
      DIUN_NOTIF_DISCORD_WEBHOOKURLFILE: /run/secrets/discord_webhook_url
      DIUN_NOTIF_GOTIFY_ENDPOINT: "https://gotify.${INTERNAL_DOMAIN:?error}"
      DIUN_NOTIF_GOTIFY_TOKENFILE: /run/secrets/gotify_token
    networks:
      - outgoing
      - socket-proxy-diun
    labels:
      diun.enable: true

secrets:
  discord_webhook_url:
    environment: DISCORD_WEBHOOK_URL
  gotify_token:
    environment: DIUN_GOTIFY_TOKEN

volumes:
  data:

networks:
  outgoing:
  socket-proxy-diun:
    external: true
