services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - socket-proxy:/var/run:ro
      - data:/data
    environment:
      TZ: "America/Toronto"
      DIUN_WATCH_SCHEDULE: 0 */12 * * * # Every 12 hours
      DIUN_PROVIDERS_DOCKER: true
      DIUN_NOTIF_DISCORD_WEBHOOKURL: ${DISCORD_WEBHOOK_URL:?error}
    labels:
      diun.enable: true
    restart: always

volumes:
  data:
  socket-proxy:
    external: true
