services:
  it-tools:
    image: ghcr.io/sharevb/it-tools:stable
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/ -o /dev/null || exit 1"]
      start_period: 30s
      start_interval: 5s
      interval: 30s
    networks:
      - proxy-internal
    labels:
      diun.enable: true
      diun.watch_repo: false
      diun.include_tags: ^stable$
      sablier.enable: true
      sablier.group: tools
      caddy: "{$$WILDCARD_INTERNAL}"
      caddy.import: service_proxy tools
      caddy.import.import: sablier tools dynamic
      caddy.import.reverse_proxy: "{{ upstreams 8080 }}"
      homepage.group: Tools
      homepage.name: IT Tools
      homepage.icon: it-tools-light
      homepage.href: https://tools.{{HOMEPAGE_VAR_INTERNAL_DOMAIN}}
      homepage.description: Developer and IT utilities
      homepage.weight: 400

networks:
  proxy-internal:
    external: true
