services:
  caddy:
    image: caddy:custom
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?error}
      EXTERNAL_DOMAIN: ${EXTERNAL_DOMAIN:?error}
      PROXY_HOST_URL: ${PROXY_HOST_URL:?error}
      ACCESS_CHECK_SUBDOMAIN: ${ACCESS_CHECK_SUBDOMAIN:?error}
      HOME_ASSISTANT_SUBDOMAIN: ${HOME_ASSISTANT_SUBDOMAIN:?error}
      HOME_ASSISTANT_PORT: ${HOME_ASSISTANT_PORT:?error}
      SPOTIFY_DASH_FRONT_SUBDOMAIN: ${SPOTIFY_DASH_FRONT_SUBDOMAIN:?error}
      SPOTIFY_DASH_FRONT_PORT: ${SPOTIFY_DASH_FRONT_PORT:?error}
      SPOTIFY_DASH_BACK_SUBDOMAIN: ${SPOTIFY_DASH_BACK_SUBDOMAIN:?error}
      SPOTIFY_DASH_BACK_PORT: ${SPOTIFY_DASH_BACK_PORT:?error}
volumes:
  caddy_data:
    external: true
  caddy_config:
