services:
  pingvin-share-x:
    image: ghcr.io/smp46/pingvin-share-x:v1
    restart: always
    configs:
      - source: config
        target: /opt/app/config.yaml
    volumes:
      - data:/opt/app/backend/data
    environment:
      TRUST_PROXY: true
    networks:
      - proxy-internal
      - proxy-pingvin-share-x
    labels:
      diun.enable: true
      caddy: "{$$WILDCARD_INTERNAL}"
      caddy.import: service_proxy share
      caddy.import.reverse_proxy: "{{ upstreams 3000 }}"
      homepage.group: Media
      homepage.name: Pingvin Share X
      homepage.icon: pingvin-share-x
      homepage.href: https://share.{{HOMEPAGE_VAR_INTERNAL_DOMAIN}}
      homepage.description: Temporary file sharing
      homepage.weight: 100

configs:
  config:
    content: |
      # Ref: https://github.com/smp46/pingvin-share-x/blob/main/config.example.yaml
      general:
        appUrl: https://${PINGVIN_SHARE_X_EXTERNAL_SUBDOMAIN:?error}.${EXTERNAL_DOMAIN:?error}
        secureCookies: "true"
        showHomePage: "false"
        sessionDuration: 1 day
        defaultLanguage: en-US
      share:
        allowRegistration: "false"
        allowUnauthenticatedShares: "false"
        maxExpiration: 1 month
        defaultExpiration: 7 days
        shareIdLength: "12"
        maxSize: "${PINGVIN_SHARE_X_MAX_SHARE_BYTES:-1000000000}" # 1 GB default
        zipCompressionLevel: "9"
        chunkSize: "10000000" # 10 MB
        autoOpenShareModal: "false"
        reverseShareSimpleOnly: "false"
        allowAdminAccessAllShares: "true"
        enableUserRecipients: "false"
        fileRetentionPeriod: 0 days
      cache:
        redis-enabled: "false"
      email:
        enableShareEmailRecipients: "true"
        enableShareDownloadNotifications: "true"
        shareRecipientsReplyToCreator: "true"
        enableEmailVerification: "true"
      smtp:
        enabled: "true"
        allowUnauthorizedCertificates: "false"
        host: "${SMTP_HOST_ADDR:?error}"
        port: "${SMTP_HOST_PORT:?error}"
        email: "${SMTP_EMAIL:?error}"
        username: "${SMTP_USER_NAME:?error}"
        password: "${SMTP_USER_PWD:?error}"
      ldap:
        enabled: "false"
      oauth:
        allowRegistration: "true"
        ignoreTotp: "true"
        disablePassword: "true"
        github-enabled: "false"
        google-enabled: "false"
        microsoft-enabled: "false"
        discord-enabled: "false"
        oidc-enabled: "true"
        oidc-discoveryUri: "https://id.${INTERNAL_DOMAIN:?error}/.well-known/openid-configuration"
        oidc-signOut: "true"
        oidc-scope: openid email profile groups
        oidc-usernameClaim: "preferred_username"
        oidc-roleGeneralAccess: "users"
        oidc-roleAdminAccess: "admins"
        oidc-clientId: "${PINGVIN_SHARE_X_OIDC_CLIENT_ID:?error}"
        oidc-clientSecret: "${PINGVIN_SHARE_X_OIDC_CLIENT_SECRET:?error}"
      s3:
        enabled: "false"
      legal:
        enabled: "false"
      initUser:
        enabled: false

volumes:
  data:

networks:
  proxy-internal:
    external: true
  proxy-pingvin-share-x:
    external: true
