services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - client_secret
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      TINYAUTH_UI_TITLE: Authentication Proxy
      TINYAUTH_APPURL: https://auth.${INTERNAL_DOMAIN:?error}
      TINYAUTH_ANALYTICS_ENABLED: true
      TINYAUTH_RESOURCES_ENABLED: false
      TINYAUTH_AUTH_SECURECOOKIE: true
      TINYAUTH_AUTH_SESSIONEXPIRY: ${TINYAUTH_SESSION_EXPIRY:-14400} # 4 hours by default
      TINYAUTH_OAUTH_AUTOREDIRECT: pocketid
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: Pocket ID
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ${TINYAUTH_CLIENT_ID:?error}
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRETFILE: /run/secrets/client_secret
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: https://id.${INTERNAL_DOMAIN:?error}/authorize
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: https://id.${INTERNAL_DOMAIN:?error}/api/oidc/token
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: https://id.${INTERNAL_DOMAIN:?error}/api/oidc/userinfo
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: https://auth.${INTERNAL_DOMAIN:?error}/api/oauth/callback/pocketid
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: openid email profile groups
      TINYAUTH_LOG_LEVEL: ${TINYAUTH_LOG_LEVEL:-info}
    networks:
      - proxy-internal
      - socket-proxy-tinyauth
    labels:
      diun.enable: true
      caddy: "{$$WILDCARD_INTERNAL}"
      caddy.import: service_proxy auth
      caddy.import.reverse_proxy: "{{ upstreams 3000 }}"
      socket-proxy.allow.get: (/v1\.\d{1,2})?/(_ping|containers/(json|[\w.-]+/json)(\?\S+)?)
      socket-proxy.allow.head: (/v1\.\d{1,2})?/_ping
      homepage.group: Authentication
      homepage.name: Tinyauth
      homepage.icon: tinyauth
      homepage.href: https://auth.{{HOMEPAGE_VAR_INTERNAL_DOMAIN}}
      homepage.description: Authentication proxy
      homepage.weight: 100

secrets:
  client_secret:
    environment: TINYAUTH_CLIENT_SECRET

networks:
  proxy-internal:
    external: true
  socket-proxy-tinyauth:
    external: true
