services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    restart: unless-stopped
    ports:
      - "${PORT:?error}:8080"
    volumes:
      - ./data/configs:/configs
      - ./data/training-data:/usr/share/tessdata
      - ./data/logs:/logs/
      - ./data/pipeline:/pipeline/
    environment:
      # Ref: https://docs.stirlingpdf.com/Advanced%20Configuration/How%20to%20add%20configurations
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true
      LANGS: enUS,en_GB
      SECURITY_CSRFDISABLED: false
      LEGAL_TERMSANDCONDITIONS: ''
      LEGAL_PRIVACYPOLICY: ''
      SYSTEM_SHOWUPDATE: true
      SYSTEM_ENABLEANALYTICS: true
      UI_APPNAME: PDF Tools
      UI_HOMEDESCRIPTION: A locally hosted one-stop-shop for all your PDF needs.
      UI_APPNAMENAVBAR: PDF Tools
