services:
  beszel:
    image: henrygd/beszel:latest
    restart: unless-stopped
    volumes:
      - data:/beszel_data
      - beszel-socket:/beszel_socket
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 5s
      interval: 120s
    environment:
      APP_URL: "https://beszel.${INTERNAL_DOMAIN:?error}"
      SHARE_ALL_SYSTEMS: true
    networks:
      - proxy-internal
    labels:
      diun.enable: true
      caddy: "beszel.{$$INTERNAL_DOMAIN}"
      caddy.reverse_proxy: "{{ upstreams 8090 }}"

  beszel-local-agent:
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    depends_on:
      beszel:
        condition: service_healthy
    network_mode: host
    volumes:
      - beszel-socket:/beszel_socket
      - socket-proxy:/var/run:ro
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 5s
      interval: 120s
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: "${BESZEL_LOCAL_AGENT_KEY:?error}"
    labels:
      diun.enable: true

volumes:
  data:
  beszel-socket:
  socket-proxy:
    external: true

networks:
  proxy-internal:
    external: true
