services:
  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0
    restart: unless-stopped
    volumes:
      - data:/beszel_data
      - beszel-socket:/beszel_socket
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 5s
      interval: 120s
    networks:
      - proxy-internal
    environment:
      APP_URL: "https://beszel.${INTERNAL_DOMAIN:?error}"
      SHARE_ALL_SYSTEMS: true
      USER_CREATION: true
    labels:
      diun.enable: true
      caddy: "beszel.{$$INTERNAL_DOMAIN}"
      caddy.reverse_proxy: "{{ upstreams 8090 }}"

  beszel-local-agent:
    image: ghcr.io/henrygd/beszel/beszel-agent:0
    restart: unless-stopped
    depends_on:
      beszel:
        condition: service_healthy
    network_mode: host
    volumes:
      - beszel-socket:/beszel_socket
      - socket-proxy:/socket-proxy:ro
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 5s
      interval: 120s
    secrets:
      - agent_key
    environment:
      LISTEN: /beszel_socket/beszel.sock
      DOCKER_HOST: unix:///socket-proxy/docker.sock
      HUB_URL: "https://beszel.${INTERNAL_DOMAIN:?error}"
      KEY_FILE: /run/secrets/agent_key
      TOKEN: ${BESZEL_LOCAL_AGENT_TOKEN:?error}
    labels:
      diun.enable: true

secrets:
  agent_key:
    environment: BESZEL_LOCAL_AGENT_KEY

volumes:
  data:
  beszel-socket:
  socket-proxy:
    external: true

networks:
  proxy-internal:
    external: true
